[ios] Using enums instead of raw int.
beloal/omim pull request #3
Opened 2018-06-27 10:39 UTC by vmihaylenko

2018-06-27 11:41 UTC, rokuz approved these changes

2018-06-27 11:44 UTC, vmihaylenko commented
@beloal ptal

2018-06-27 12:26 UTC, beloal requested changes

2018-06-27 12:26 UTC, beloal commented on iphone/Maps/Bookmarks/BookmarksVC.mm
> +- (NSIndexPath *)tableView:(UITableView *)tableView willSelectRowAtIndexPath:(NSIndexPath *)indexPath
Этот метод не нужен, ты сам просил убрать в оригинальном PR

2018-06-27 13:13 UTC, vmihaylenko commented on iphone/Maps/Bookmarks/BookmarksVC.mm
> +- (NSIndexPath *)tableView:(UITableView *)tableView willSelectRowAtIndexPath:(NSIndexPath *)indexPath
эх, ребейз :(

2018-06-28 10:51 UTC, vmihaylenko commented
@beloal ptal

2018-06-28 10:59 UTC, beloal approved these changes

2018-06-28 10:59 UTC, merged